//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.Leilao.Dominio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeilaoContext : DbContext
    {
        public LeilaoContext()
            : base("name=LeilaoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Negociacao> Negociacaos { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
